### ISSUE TITLE
Networks missing in Docker::Container.get?

### ISSUE THREAD

**Issue by okleinschmidt** [swipely/docker-api#466] opened 2017-01-16 19:26 UTC
Hi there,

if I do a curl to /containers/mycontainer/json I get the NetworkSettings which includes my private docker subnet, if I use Docker::Container.get('mycontainer') the "Networks" block shown below is completely missing. Maybe I'm doing something wrong? This occurs only if a custom subnet is used for the container.

cheers,
Ole

```javascript
"NetworkSettings": {
    "Bridge": "",
    "SandboxID": "fb8cfee04a659449a9da2c23bc3ba6a70677868e5cf7c2e4eb78a8ca6afcbc00",
    "HairpinMode": false,
    "LinkLocalIPv6Address": "",
    "LinkLocalIPv6PrefixLen": 0,
    "Ports": {
      "3389/tcp": null,
      "8080/tcp": null
    },
    "SandboxKey": "/var/run/docker/netns/fb8cfee04a65",
    "SecondaryIPAddresses": null,
    "SecondaryIPv6Addresses": null,
    "EndpointID": "",
    "Gateway": "",
    "GlobalIPv6Address": "",
    "GlobalIPv6PrefixLen": 0,
    "IPAddress": "",
    "IPPrefixLen": 0,
    "IPv6Gateway": "",
    "MacAddress": "",
    "Networks": {
      "mysubnet": {
        "IPAMConfig": {
          "IPv4Address": "172.18.0.200"
        },
        "Links": null,
        "Aliases": [
          "3f2126edc7ff"
        ],
        "NetworkID": "523bff900442646b884d3299c34df99164452ef411668fde94a7944384131dc4",
        "EndpointID": "159892f7a83ae4af41d2590e302cc113fba6e49a49e89e3bd35610f654b5e920",
        "Gateway": "172.18.0.1",
        "IPAddress": "172.18.0.200",
        "IPPrefixLen": 24,
        "IPv6Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "MacAddress": "02:42:ac:12:00:c8"
      }
    }
```

**Comment by muskovicsgabor** [comment] 2017-05-12 15:26
+1

**Comment by muskovicsgabor** [comment] 2017-05-13 08:03
`    Docker::Container.all.each do |container|
      c = container.json
      ip_address = container.info['NetworkSettings']['Networks'][container.info['HostConfig']['NetworkMode']]['IPAddress']
`
But I can't get the ip_address from the json version.

**Comment by xsresearch** [comment] 2017-05-14 23:23
This behaviour seems to be consistent with the json returned from api calls to the docker daemon when a user defined network is specified.

Version information used:
<pre>
{"Version":"1.12.5","ApiVersion":"1.24","GitCommit":"7392c3b","GoVersion":"go1.6.4","Os":"linux","Arch":"amd64","KernelVersion":"4.7.0","BuildTime":"2016-12-16T02:30:42.893103237+00:00"}
</pre>
A call to /containers/mycontainer/json returns IPAddress of an empty string
But a call to /containers/json has a correctly populated IPAddress field

A previous related issue regarding changing the merge order of top level and detailed hashes was reported in #416 and resolving in #418 and may have contributed to this issue. 

Currently using this as a workaround where c is a container from Docker::Container.create
<pre>
name = c.json['Name']
ipaddr = Docker::Container.all.select{|x| x.info['Names'][0].eql?(name)}.first.info['NetworkSettings']['Networks']['user_defined_net1']['IPAddress']
</pre>
@okleinschmidt which versions are you running?

**Comment by take-cheeze** [comment] 2017-10-09 08:42
Seems like this behavior is caused by `Docker::API_VERSION`:
https://github.com/swipely/docker-api/blob/3c910b2b22e30ec88ea692ba5868d7875bbd85e9/lib/docker/connection.rb#L83
`.NetworkSettings.Networks` seems to be added in [1.21](https://docs.docker.com/engine/api/v1.21/) so adding:
```ruby
Docker::API_VERSION = '1.21'
```
somewhere before calling any API should make the better workaround.

BTW running `docker  inspect` by default seems to return JSON of the latest format.

**Closed** 2020-06-16 12:28 UTC
