### ISSUE TITLE
Running container.exec causes Excon connection refused, end of file reached error

### ISSUE THREAD

**Issue by jayantbh** [swipely/docker-api#442] opened 2016-08-25 18:24 UTC
I can run other commands normally. I can create containers, archive in files, get info, etc. But I can't run exec. What's wrong here? 

docker exec on the command line works fine too.
And Docker API works fine on localhost too.

```
[4] pry(#<***>)> container.exec(["bash","-c","ls"])
Excon::Error::Socket: end of file reached (EOFError)
from /path/to/lib/excon-0.52.0/lib/excon/socket.rb:46:in `read_nonblock'
```

Excon v0.52.0
Docker API v1.31.0
Rails v4.0.0
ruby 2.0.0p648 (2015-12-16 revision 53162) [x86_64-linux]

**Comment by jayantbh** [comment] 2016-08-27 12:35
So, if anyone faces this later, I cooked up this workaround to deal with this:

```ruby
def docker_container_exec(container,command)
    stdout = []
    stderr = []
    begin
      container.exec(["bash","-lc",command]){ |stream, chunk|
        if stream.to_s == 'stdout'
          stdout.push chunk
        elsif stream.to_s == 'stderr'
          stderr.push chunk
        end
      }
    rescue
      nil
    end
    {stdout: stdout, stderr: stderr[1..-1]}
  end
```

**Comment by jayantbh** [comment] 2016-08-27 19:17
@tlunter any ideas about how to actually fix this?

**Comment by hekaldama** [comment] 2016-09-13 15:20
@jayantbh what docker daemon version are you talking to?

**Comment by hekaldama** [comment] 2016-09-13 15:28
I am running:

Excon 0.52.0
Docker API 1.31.0
Ruby 2.1.2p95
Docker engine 1.12.0

and the following works:
```ruby
Docker::Container.create(
  'Image' => 'alpine', 'Cmd' => ['ping','google.com']
).start.exec(
  ['ash','-lc','ls']
) # => [["bin\n", "dev\netc\nhome\nlib\nlinuxrc\nmedia\nmnt\nproc\nroot\nrun\nsbin\nsrv\nsys\ntmp\nusr\nvar\n"], [], 0]
```
What image are you using? Did you start the container?

**Comment by jayantbh** [comment] 2016-09-13 20:25
Daemon version 1.12.1
Image: jayantbh/ubuntu-max
Yes, always started the container.

**Comment by hekaldama** [comment] 2016-09-13 20:25
Does my example work for you?

**Comment by jayantbh** [comment] 2016-09-14 13:23
I didn't try it yet, however, do you suggest that using `ping google.com` as an entrypoint might fix the problem I'm facing?

Side note: Your exec command has a typo, **ash** instead of **bash**.

**Comment by hekaldama** [comment] 2016-09-14 13:28
@jayantbh the `alpine` image does not come with bash by default. It does come with [ash](https://en.wikipedia.org/wiki/Almquist_shell). I use `alpine` in this example because it is ~5MB and very simple.

I was using `ping` just as a way to keep the container running while I `exec` other commands on it. If you don't use something that will keep the container running, then it will be in a stopped state.

This making sense at all?

**Comment by hekaldama** [comment] 2016-09-14 13:32
Also, if you can reproduce this reliably, can you attach your full script / code / link to code as well as what `docker ps` and `docker inspect $CONTAINER` is showing you at this time?

**Comment by jayantbh** [comment] 2016-09-22 19:06
@hekaldama I'll have to send you the script later. Thanks for the info on alpine and ash, didn't know about it. I used two things as entrypoints at different times. `tail -f /dev/null` and `bash` (not exactly `bash`, but something very close), both seemed to work in the same way, resulting in the same outcome.

**Comment by hekaldama** [comment] 2016-09-22 19:29
Cool. Keep us posted.

**Closed** 2019-07-08 11:19 UTC
